### ISSUE TITLE
Compilation of ROS2 packages with messages fails with `--symlink-install`

### ISSUE THREAD

**Issue by galou** [continental/rmw_ecal#2]
CMake complains about non-existing library `$ROS2_WORKSPACE/install/lib/rmw_ecal_dynamic_cpp.so`, though the file exists but is a symlink.

A work-around is to copy the library in place of the symlink.

Please note that I'm using CMake 3.10 as this is the version provided by a package on Ubuntu 18.04.

**Comment by brakmic-aleksandar** [comment]
I've just tried it on my machine (Ubuntu 18.04) and it seemed to work fine, although i'm using CMake 3.18, what ROS distro are you using?

**Comment by rex-schilasky** [comment]
I've build and used the rmw successful on Ubuntu 18 following the instructions. So from my point of view we can close that issue if @galou can not give any new input.

**Comment by galou** [comment]
I don't have the capability to test this further, sorry. Closing the issue.
