### ISSUE TITLE
Windows 10 support?

### ISSUE THREAD

**Issue by james-yoo** [continental/rmw_ecal#20]
Hi,

I would like to test rmw_ecal in Windows 10(ROS2 Foxy). I have installed eCAL 5.8.12 with binary installation.
But build failed when compiling rmw_ecal_shared_cpp.
Followings are log messages(stdout.txt) in 'log' folder :
 
C:\eCAL\include\ecal/pb/monitoring.pb.h(17,1): fatal error C1189: #error:  This file was generated by an older version of protoc which is ( C:\opt\workspace\src\rmw_ecal-1.0.0\rmw_ecal_shared_cpp\src\get_node_info_and_types.cpp) [C:\opt\workspace\build\rmw_ecal_shared_cpp\rmw_ecal_shared_cpp.vcxproj]
C:\eCAL\include\ecal/pb/monitoring.pb.h(17,1): fatal error C1189: #error:  This file was generated by an older version of protoc which is ( C:\opt\workspace\src\rmw_ecal-1.0.0\rmw_ecal_shared_cpp\src\get_service_names_and_types.cpp) [C:\opt\workspace\build\rmw_ecal_shared_cpp\rmw_ecal_shared_cpp.vcxproj]
C:\eCAL\include\ecal/pb/monitoring.pb.h(17,1): fatal error C1189: #error:  This file was generated by an older version of protoc which is ( C:\opt\workspace\src\rmw_ecal-1.0.0\rmw_ecal_shared_cpp\src\get_topic_names_and_types.cpp) [C:\opt\workspace\build\rmw_ecal_shared_cpp\rmw_ecal_shared_cpp.vcxproj]
C:\eCAL\include\ecal/pb/monitoring.pb.h(17,1): fatal error C1189: #error:  This file was generated by an older version of protoc which is ( C:\opt\workspace\src\rmw_ecal-1.0.0\rmw_ecal_shared_cpp\src\rmw.cpp) [C:\opt\workspace\build\rmw_ecal_shared_cpp\rmw_ecal_shared_cpp.vcxproj]

**Comment by FlorianReimold** [comment]
Hi james-yoo,

eCAL 5.8.12 for Windows ships with protobuf 3.11.4 (both protoc and libprotobuf). The .pb.h files we ship with eCAL are created with that exact verison. Somehow however your system seems to find another libprotobuf version that is newer than the one from eCAL.

CMake should at some point tell you about the libprotobuf version that it found:

![protobuf](https://user-images.githubusercontent.com/11774314/126115260-66424b6b-d2ff-4d31-9e19-7d827ea23336.png)

Did it find the protobuf from eCAL?

**Comment by james-yoo** [comment]
Hi @FlorianReimold,
Thanks for your feedback. As you pointed out, this issue caused by version mismatch.

First, I checked the protoc version as follow(it shows version 3.11.4):
```
$ protoc --version  
libprotoc 3.11.4
```
However, protobuf version changed after activating the ROS2 environment.
(As you know, ROS2 environment should be activated before compile the rmw_ecal packages)
```
$ call c:\opt\ros\foxy\x64\setup.bat  
$ protoc --version  
libprotoc 3.12.3
```
Is it a problem regarding of the ROS2 environment setup? I installed ROS2 Foxy on Windows 10 as guided below:
https://ms-iot.github.io/ROSOnWindows/GettingStarted/SetupRos2.html

**Comment by FlorianReimold** [comment]
Hm, looks like ROS2 for Windows ships its own protobuf version, just the way we do with eCAL. When using ROS and eCAL at the same time however you get conflicting versions. The file (`monitoring.pb.h`) your system is complaining about is an autogenerated file that is installed by eCAL. I have to admit that this is probably wasn't the greatest design choice.

A quick solution that should work perfectly is to adapt either one to the protobuf version of the other. As I don't know how to compile a ROS setup, I have compiled eCAL 5.8.12 against protobuf 3.12.3 and attached the installer for you to test. For the future I will check how to avoid exposing the exact protobuf dependency in eCAL, but that topic will take some time.

https://drive.google.com/file/d/1YVQTANcpYpzWeG0VZ5ZGDoiggvfH0VFE/view?usp=sharing
Pass: 1234 (Apparently google drive checks for exe files in zips and prevents sharing)

On Ubuntu neither ROS2 nor eCAL ships its own protobuf, as it is already present in the apt repository. That's why everything works fine on Ubuntu.

**Comment by james-yoo** [comment]
Hi @FlorianReimold ,
Thanks for the quick response! I will try a test binary that you provided.

**Comment by FlorianReimold** [comment]
Can you tell me if this solves your problem?

**Comment by james-yoo** [comment]
Hi @FlorianReimold,

After uninstall eCAL 5.8.12(protobuf 3.11.4 version), I installed binary which you provided and reboot.
Following is the step after reboot (rmw_ecal package is located c:\opt\workspace\src).
```
$ call c:\opt\ros\foxy\x64\setup.bat  
$ protoc --version  
libprotoc 3.12.3
$ cd c:\opt\workspace
$ colcon build
```
Unfortunately, rmw_ecal_shared_cpp still can not compile. 
I attached build log which is generated in 'log' folder of workspace as below:
[streams.log](https://github.com/continental/rmw_ecal/files/6849065/streams.log)

**Comment by FlorianReimold** [comment]
Well, at least it went through the cmake step ;)

Which Visual Studio version are you using? I accidentally built eCAL with VS 2019 (v142 toolset). The official eCAL binaries we provide for download are Visual Studio 2015 (v140 toolset).

**Comment by metabotics** [comment]
Hi @FlorianReimold ,

I am using Visual Studio 2019 and CMake version is 3.18

**Comment by james-yoo** [comment]
Hi @FlorianReimold ,

I am using Visual Studio 2019 and CMake 3.18 version.

**Comment by FlorianReimold** [comment]
Hm, strange, OK, can you try again with a build created by our CI?
https://github.com/continental/ecal/actions/runs/1049309961

That one is build with the v140 toolset and should therefore provide better compatibility. And please clean your build / cmake directory before trying again.

**Comment by james-yoo** [comment]
Unfortunately, new binary with v140 toolset is not working. 
Build log shows same error as I attached before.

To avoid the protobuf dependency, I think either eCAL or ROS2 should build from source.

**Comment by FlorianReimold** [comment]
Yea, exactly. I talked to a colleague yesterday. And even though we think that one could theoretically hide protobuf well enough to make this work, we came to the conclusion that the proper way is to build eCAL with the ROS2 toolchain. So you would get all the same libraries that ROS uses.

**Comment by brakmic-aleksandar** [comment]
Has this been solved? Can i close it?

**Comment by Kerstin-Keller** [comment]
I discussed with @FlorianReimold that it might be worthwile to add ecal as a submodule to be build as part of ecal_rmw (only the core, of course). In general, it should be possible to set the appropriate parameters from the top-level CMake files.

**Comment by brakmic-aleksandar** [comment]
Yeah, that's seems like a good idea to me aswell, i'll create new issue for that.

**Comment by brakmic-aleksandar** [comment]
I've created issue for eCAL submodule and i'm closing this one.
