### ISSUE TITLE
Duplicate EXPORT option in CMake file

### ISSUE THREAD

**Issue by ZoltanCsibi** [continental/rmw_ecal#23]
The CMakeLists file from rmw_ecal_shared_cpp uses twice the EXPORT option in the [install command](https://github.com/continental/rmw_ecal/blob/53336382647387df8f49abf5324e8aac562cabcf/rmw_ecal_shared_cpp/CMakeLists.txt#L107).

This fails with CMake 3.12.18081601-MSVC_2 (the Visual Studio 2017 flavor) with the error:
`
CMake Error at CMakeLists.txt:105 (install):
  install TARGETS given unknown argument "EXPORT".
`

**Comment by brakmic-aleksandar** [comment]
Fixed.
