### ISSUE TITLE
Drop support for Dashing and Eloquent

### ISSUE THREAD

**Issue by brakmic-aleksandar** [continental/rmw_ecal#40]
Drop support for Dashing and Eloquent ROS2 distros since they are deprecated, also create separate branches named legacy/distro_name that should contain old code that supports them.

**Comment by ZhenshengLee** [comment]
Add: set master branch as the rolling branch, even we can rename master to rolling.

Let's take https://github.com/ros2/rmw_iceoryx as an example.

**Comment by brakmic-aleksandar** [comment]
Yeah, i agree, but i would like to have this kind of structure:

```
legacy/dashing
legacy/eloquent
master
```
Reason i haven't added galactic and foxy branches is because rmw_ecal is designed so user doesn't have to worry about what distro they are cloning it for (as long as it is currently supported, right now you can clone rmw_ecal into any dashing/eloquent/foxy/galactic workspace and it will build without any of branch management/flags) so having branches for currently supported distros should make managing it  more complicated and error prone and if user doesn't want to use rolling release of rmw_ecal they should just use one of releases (which should be released more frequently, i know :( ).

**Comment by brakmic-aleksandar** [comment]
I'm planning to start using this system after next release which should happen when eCAL5.10 releases and to drop support for aforementioned distros after next release of rmw_ecal.

**Comment by brakmic-aleksandar** [comment]
Done!
